apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: codegenagain
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegenagain
  name: codegenagain
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: codegenagain
    weight: 100
  wildcardPolicy: None
